//WARNING: This file is auto generated by the routes generator.

class RoutesManager {
  static const String loginScreen = '/loginScreen';
  static const String chatScreen = '/chatScreen';
  static const String welcomeScreen = '/welcomeScreen';
  static const String opionsScreen = '/opionsScreen';
  static const String supportScreen = '/supportScreen';
  static const String aboutScreen = '/aboutScreen';
  static const String onboardingScreen = '/onboardingScreen';
}
